#Python Automated Tests
language: python
python:
  - "2.7"
  - "pypy"
install:
  - "pip install apscheduler pyzmq"
script:
  -python testserver.py &
  -python 0-meter.py ping.xml
  -cat ping.log
  -python 0-meter.py config.xml
  -cat hello_world.log
