#Python Automated Tests
language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
install:
  - "pip install apscheduler pyzmq kafka-python"
script:
  - python ci/scripts/testserver.py &
  - python 0-meter.py config.xml
  - cat hello_world.log
  - python 0-meter.py ci/ping.xml
  - cat ping.log
  - cat thanks.csv
  - python 0-meter.py ci/csv_test.xml
  - cat csv_test.log
  - ci/scripts/bad_ping_test.sh
  - cat ping_bad.log
  - cat ping_bad.csv
